### ISSUE TITLE
2.1.4章のサンプルファイルがダウンロードできず、サンプルコードが動きません

### ISSUE THREAD

**Issue by hyga2c** [makaishi2/python-text-anl-book-info#1]
2.1.4章のサンプルコードで提示いただいているサンプルファイル（PDF, Word)の参照先である`https://github.com/makaishi2/text-anl-samples/`が存在しないため、404エラーが返ってきてしまいます。

**Comment by makaishi2** [comment]
ご迷惑をおかけして大変申し訳ありませんでした。
書籍で参照していたことを失念して、間違ってリポジトリを削除してしまったことが原因です。
リポジトリは戻したのですが、諸般の事象でオリジナルのデータがなくなってしまい、PDFとDOCXは新たに起こしています。
その関係で、結果が紙面と多少異なってしまっていますが、その点についてはご理解いただきたく思います。
よろしくお願いいたします。

**Comment by hyga2c** [comment]
早速のご対応をいただきありがとうございました。
